POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"trilxag",
    "password":"123456",
    "email":"trilxag1003@gmail.com",
    "phone":"0903234765"
}

#########################################
POST http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username":"trilxag",
    "password":"123456"
}
###
POST http://localhost:5000/api/auth/user/login
Content-Type: application/json


{
    "username":"trilxag",
    "password":"123456"
}
####
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdXN0b21lcklkIjoiNjFiNjJlZTRiMGMxMjQ3OTkxM2NiZWJjIiwiUm9sZSI6IlVzZXIiLCJpYXQiOjE2Mzk3MTM1MDQsImV4cCI6MTYzOTc5OTkwNH0.Y9if--dxdmdS6dKYaFV4fsoz2d229Huu6FCK0RCRQ8c"
}
####
POST https://blooming-mountain-13837.herokuapp.com/api/auth/verifyEmail/61bc0c4cea07ff64763f3474
#########################################
POST http://localhost:5000/api/products/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdXN0b21lcklkIjoiNjFiNjJlZTRiMGMxMjQ3OTkxM2NiZWJjIiwiUm9sZSI6IlVzZXIiLCJpYXQiOjE2Mzk3MTMxNDMsImV4cCI6MTYzOTcxMzIwM30.meAsJyKAkbpKRYtDnSsEqywI6WIHm4J4l-r0wnbgdKc

{
   "name":"Royal Canin Urinary S/O – Thức Ăn Hạt Cho Mèo Bị Sỏi Thận",
   "idBrand":"619f03c1e5d60328d18f4e62",
   "price":300000,
   "imageRepresent":[
        {
            "fieldname": "imageRepresent",
            "originalname": "02190f4d6ad0a28efbc1.jpg",
            "encoding": "7bit",
            "mimetype": "image/jpeg",
            "destination": "C:\\Users\\TRINGU~1\\AppData\\Local\\Temp",
            "filename": "43688e5d362e34ce312a8532f9cb0d0b",
            "path": "C:\\Users\\TRINGU~1\\AppData\\Local\\Temp\\43688e5d362e34ce312a8532f9cb0d0b",
            "size": 1385107
        }
    ],
    "listImage":[{
             "fieldname": "listImage",
            "originalname": "02190f4d6ad0a28efbc1.jpg",
            "encoding": "7bit",
            "mimetype": "image/jpeg",
            "destination": "C:\\Users\\TRINGU~1\\AppData\\Local\\Temp",
            "filename": "43688e5d362e34ce312a8532f9cb0d0b",
            "path": "C:\\Users\\TRINGU~1\\AppData\\Local\\Temp\\43688e5d362e34ce312a8532f9cb0d0b",
            "size": 1385107
    }],
   "warehouses":[
       {
           "color":"#ff0000",
           "amoutImport":300,
           "priceImport":100000
       },
       {
           "color":"#ffff00",
           "amoutImport":300,
           "priceImport":30000
       }
   ],
   "titleFeature":"title Feature",
   "contentFeature":"content Feature",
   "titleDescribe":"title Describe",
   "contentDescribe":"content Describe"
}
#####
GET http://localhost:5000/api/products/nnnn
######
PUT http://localhost:5000/api/products/61968a52c3f081542e91b764
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdXN0b21lcklkIjoiNjFhZWUxODU2YWQ5NmNiN2FlZGFmNGM1IiwiUm9sZSI6IjYxYWVkM2IzNzgxMmZhMDY4ZWVlNmQ0OSIsImlhdCI6MTYzODg2OTIyNH0.H8CE0J4mBmLCYlVmN455sHtJDJu7t4I4k2Pc-JrmV5U

{
   "name":"Royal Canin Urinary S/O – Thức Ăn Hạt Cho Mèo Bị Sỏi Thận",
   "brand":"Royal Canin",
   "price":500000,
   "imageRepresent":"https://scontent.fsgn2-2.fna.fbcdn.net/v/t39.30808-6/p843x403/257544041_1976106609229359_1434567248597624283_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=825194&_nc_ohc=HwZDgZ99_l0AX_5t8us&_nc_ht=scontent.fsgn2-2.fna&oh=c96b976c0eff50f86cebf71560681717&oe=619829E9",
   "titleFeature":"update title Feature",
   "contentFeature":"update content Feature",
   "titleDescribe":"update title Describe",
   "contentDescribe":" update content Describe"
}
######
GET http://localhost:5000/api/products

#####
GET  http://localhost:5000/api/products/search?search=product2

####
GET  http://localhost:5000/api/products/sortPrice?sort=-1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdXN0b21lcklkIjoiNjFiNjJlZTRiMGMxMjQ3OTkxM2NiZWJjIiwiUm9sZSI6IlVzZXIiLCJpYXQiOjE2Mzk3MTM1ODYsImV4cCI6MTYzOTcxMzY0Nn0.oInn5Tci-oCc0DS_DOnuBtBWRlNS_FT0XqE_gw8NmDU
####
GET http://localhost:5000/api/category
####
GET http://localhost:5000/api/category/ca
####
GET http://localhost:5000/api/category/detail/cho
####
POST https://blooming-mountain-13837.herokuapp.com/api/category/store
Content-Type: application/json

{
    "name":"chó"
}
####
GET https://blooming-mountain-13837.herokuapp.com/api/category/edit/ca
####
PUT https://blooming-mountain-13837.herokuapp.com/api/category/update/619ded9067fe4b8f9e74f266
Content-Type: application/json

{
    "name":"hưu cao cổ"
}
####

DELETE  http://localhost:5000/api/category/delete/619e62b87dfe3a2e6e3f2157
####
GET http://localhost:5000/api/subcategory

####
GET http://localhost:5000/api/subcategory/do-trang-tri-cho-cho
###
GET http://localhost:5000/api/subcategory/detail/do-trang-tri-be-ca

####
GET http://localhost:5000/api/subcategory/create
####
POST http://localhost:5000/api/subcategory/store
Content-Type: application/json

{
    "name":"Đồ trang trí cho chó",
    "category":"chó"
}
####
GET http://localhost:5000/api/subcategory/edit/chuong-cho
####
PUT http://localhost:5000/api/subcategory/update/619df80c6f8ec98d6c55b2fa
Content-Type: application/json

{
    "name":"Chuồng chó",
    "category":"Chó"
}
####
DELETE  http://localhost:5000/api/subcategory/delete/619f4e787b1dd36bcb6a36be
####
GET http://localhost:5000/api/brand
####

GET http://localhost:5000/api/brand/create
####
POST http://localhost:5000/api/brand/store
Content-Type: application/json

{
    "name":"Puma",
    "origin":"US-UK",
    "subCategory":"Đồ trang trí cho chó"
}
####
GET http://localhost:5000/api/brand/edit/gucci
####
PUT http://localhost:5000/api/brand/update/619dc4d90302efb944ab31ab
Content-Type: application/json

{
    "name":"Gucci",
    "origin":"Mỹ",
    "subCategory":"Thức ăn cho mèo"
}
####
DELETE  http://localhost:5000/api/brand/delete/619f03b9e5d60328d18f4e5d
####
GET http://localhost:5000/api/brand/detail/nutrience

####
GET http://localhost:5000/api/subcategory/search/Thức ăn cho mèo
####
GET http://localhost:5000/api/brand/search/NUTRIENCE
####
GET http://localhost:5000/api/category/search/cho
####
DELETE http://localhost:5000/api/products/delete/61a7162f8cc81d4ac311df41
####

GET http://localhost:5000/api/account/staff
####

GET http://localhost:5000/api/account/staff/create

####

GET http://localhost:5000/api/account/staff/detail/61ae34b582b9d676887665cf
####

GET http://localhost:5000/api/account/staff/edit/61ae34b582b9d676887665cf

####
GET http://localhost:5000/api/account/customer

###
GET http://localhost:5000/api/voucher
####

POST  http://localhost:5000/api/voucher/add
Content-Type: application/json

{
    "title":"Tile01",
    "name":"voucher01",
    "discount":30,
    "condition":100000,
    "desciption":"mô tả cho vouchers",
    "dateStart":"12/05/2021",
    "dateEnd":"12/07/2021"

}

####

PUT  http://localhost:5000/api/voucher/update/61a98bc9e65794f5ad5a7d59
Content-Type: application/json

{
    "title":"Tile02",
    "name":"voucher02",
    "discount":30,
    "condition":100000,
    "desciption":"mô tả cho vouchers",
    "dateStart":"03/12/2021",
    "dateEnd":"04/12/2021"

}
####
POST http://localhost:5000/api/account/staff/store
Content-Type: application/json

{
    "name":"Nguyễn Hữu Trí",
    "username":"trilxag",
    "phone":"0783432182",
    "gender":"Nam",
    "email":"trilxag1006@gmail.com",
    "address":"Địa chỉ nè",
    "permission":"User"
}
###

PUT http://localhost:5000/api/account/staff/update/61ae4da9568460183547dde8
Content-Type: application/json

{
    "permission":"Staff"
}
###
DELETE http://localhost:5000/api/account/staff/delete/61ae4a55e79913f16346fa3c

####
GET http://localhost:5000/api/permission


####
POST  http://localhost:5000/api/permission/store
Content-Type: application/json

{
    "name":"Staff"
}
####
PUT  http://localhost:5000/api/permission/update/61aed62e570a83dbfcfaa4d6
Content-Type: application/json

{
    "name":"Staff"
}
####
DELETE http://localhost:5000/api/permission/delete/61aed62e570a83dbfcfaa4d6
